CREATE TABLE IF NOT EXISTS endpoint_hits
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app      varchar   NOT NULL,
    uri      varchar   NOT NULL,
    ip       varchar   NOT NULL,
    hit_time timestamp NOT NULL
);